#!/bin/bash

echo "Grafana Configuration Instructions"
echo "==================================="
echo ""
echo "1. Open Grafana: http://192.168.121.50:32030"
echo "2. Login: admin / admin123"
echo ""
echo "3. Add Prometheus Data Source:"
echo "   - Click ⚙️ (Settings) → Data Sources"
echo "   - Click 'Add data source'"
echo "   - Select 'Prometheus'"
echo "   - URL: http://prometheus:9090"
echo "   - Click 'Save & Test'"
echo ""
echo "4. Add Loki Data Source:"
echo "   - Click 'Add data source' again"
echo "   - Select 'Loki'"
echo "   - URL: http://loki:3100"
echo "   - Click 'Save & Test'"
echo ""
echo "5. Create Dashboard:"
echo "   - Click + → Dashboard"
echo "   - Add Panel"
echo "   - Query Prometheus metrics"
echo ""
echo "✅ Your monitoring stack is ready!"
