#!/bin/bash

echo "=========================================="
echo "Pipeline Monitoring Dashboard Setup"
echo "=========================================="
echo ""
echo "1. Open Grafana: http://192.168.121.50:32030"
echo "2. Login: admin / admin123"
echo ""
echo "3. Create Dashboard for Pipeline Metrics:"
echo "   - Click + → Dashboard"
echo "   - Click 'Add Panel'"
echo ""
echo "4. Add these panels:"
echo ""
echo "Panel 1: Pipeline Success Rate"
echo "   Query: count(pipeline_status=success) / count(pipeline_status)"
echo ""
echo "Panel 2: Average Build Time"
echo "   Query: avg(build_duration_ms)"
echo ""
echo "Panel 3: Test Pass Rate"
echo "   Query: (sum(test_passed) / sum(test_total)) * 100"
echo ""
echo "Panel 4: Deployment Frequency"
echo "   Query: count(deploy_prod_status=success) over time"
echo ""
echo "5. View Logs Panel:"
echo "   - Add new panel"
echo "   - Select Loki data source"
echo "   - Query: {namespace='cicd'} |= 'Pipeline'"
echo ""
echo "=========================================="
echo "✅ Your pipeline will now show:"
echo "=========================================="
echo "📊 Performance trends (build times, test times)"
echo "🔍 Failure detection (failed tests, deployment errors)"
echo "📈 System behavior (success rates, deployment frequency)"
echo "📝 Complete logs (troubleshooting & audit trail)"
echo ""
