#!/bin/bash
set -e
cd ~/fyp-cluster


if [ ! -f ./jenkins_agent.pub ]; then
    echo "jenkins_agent.pub not found generating new SSH key..."
    ssh-keygen -t ed25519 -f ~/.ssh/jenkins_agent -N "" -q
    cat ~/.ssh/jenkins_agent.pub > ./jenkins_agent.pub
    cat ~/.ssh/jenkins_agent > ./jenkins_agent.key
else
    echo "Using SSH key generated by Vagrant..."
    cp ./jenkins_agent.key ~/.ssh/jenkins_agent
    chmod 600 ~/.ssh/jenkins_agent
fi

echo "Adding SSH key to authorized_keys..."
mkdir -p ~/.ssh
cat ./jenkins_agent.pub >> ~/.ssh/authorized_keys
sort -u ~/.ssh/authorized_keys > /tmp/auth_keys_tmp
mv /tmp/auth_keys_tmp ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys

mkdir -p ~/jenkins-agent
echo "Created ~/jenkins-agent directory"

if ! command -v java &>/dev/null; then
    echo "Installing Java..."
    sudo apt-get install -y openjdk-17-jre-headless
fi

sudo systemctl enable ssh
sudo systemctl start ssh
echo "SSH server is running"

if [ -f ./k3s.yaml ]; then
    cp ./k3s.yaml ~/k3s.yaml
    echo "Copied k3s.yaml to ~/k3s.yaml"
fi

if [ -f ./jenkins-info.txt ]; then
    echo ""
    echo '============================================'
    echo "Jenkins is ready"
    cat ./jenkins-info.txt
    echo '============================================'
fi

echo ""
echo "Done."
echo "	1. Start SDOS: cd sdos-dashboard && bash run-all.sh"
echo "  2. Open: http://localhost:5000"
echo "  3. Jenkins: http://192.168.121.40:32080"
echo "  4. Add your GitHub token to developer_workspace.py"
