#!/bin/bash
# ─── SDOS Host Setup ──────────────────────────────────────────────────────────
# Run this ONCE on the host machine after `vagrant up` completes
# This sets up the SSH key so Jenkins can connect to the host as an agent

set -e
cd ~/fyp-cluster

echo "╔══════════════════════════════════════════════════════════╗"
echo "║           SDOS — Host Setup Script                      ║"
echo "╚══════════════════════════════════════════════════════════╝"

# Check if jenkins_agent.pub was generated by Vagrant
if [ ! -f ./jenkins_agent.pub ]; then
    echo "jenkins_agent.pub not found — generating new SSH key..."
    ssh-keygen -t ed25519 -f ~/.ssh/jenkins_agent -N "" -q
    cat ~/.ssh/jenkins_agent.pub > ./jenkins_agent.pub
    cat ~/.ssh/jenkins_agent > ./jenkins_agent.key
else
    echo "Using SSH key generated by Vagrant..."
    cp ./jenkins_agent.key ~/.ssh/jenkins_agent
    chmod 600 ~/.ssh/jenkins_agent
fi

# Add public key to authorized_keys
echo "Adding SSH key to authorized_keys..."
mkdir -p ~/.ssh
cat ./jenkins_agent.pub >> ~/.ssh/authorized_keys
sort -u ~/.ssh/authorized_keys > /tmp/auth_keys_tmp
mv /tmp/auth_keys_tmp ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys

# Create jenkins-agent directory
mkdir -p ~/jenkins-agent
echo "Created ~/jenkins-agent directory"

# Install Java if not present (needed for Jenkins agent)
if ! command -v java &>/dev/null; then
    echo "Installing Java..."
    sudo apt-get install -y openjdk-17-jre-headless
fi

# Ensure SSH server is running
sudo systemctl enable ssh
sudo systemctl start ssh
echo "SSH server is running"

# Copy k3s.yaml to home for host-agent pipelines
if [ -f ./k3s.yaml ]; then
    cp ./k3s.yaml ~/k3s.yaml
    echo "Copied k3s.yaml to ~/k3s.yaml"
fi

# Show Jenkins info
if [ -f ./jenkins-info.txt ]; then
    echo ""
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║  Jenkins is ready!                                       ║"
    cat ./jenkins-info.txt | while IFS= read -r line; do
        printf "║  %-56s║\n" "$line"
    done
    echo "╚══════════════════════════════════════════════════════════╝"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Host setup complete!                                    ║"
echo "║                                                          ║"
echo "║  Next steps:                                             ║"
echo "║  1. Start SDOS: cd sdos-dashboard && bash run-all.sh     ║"
echo "║  2. Open: http://localhost:5000                          ║"
echo "║  3. Jenkins: http://192.168.121.40:32080                 ║"
echo "║  4. Add your GitHub token to developer_workspace.py      ║"
echo "╚══════════════════════════════════════════════════════════╝"
